language: python

python:
  - 3.5

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=reservas.settings.travis

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE travis_reservas;' -U postgres

script:
  - python manage.py migrate
