dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: /bin/true

db:
  image: postgres
  volumes_from:
    - dbdata

web:
  build: .
  command: /bin/bash run-django.sh
  env_file: ./environment.txt
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
